// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package org.jaiswarsecurities.iris.proto;

public interface ChipmunkRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iris.ChipmunkRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * TRADE, MARKET_DATA, FX
   * </pre>
   *
   * <code>string eventType = 1;</code>
   * @return The eventType.
   */
  java.lang.String getEventType();
  /**
   * <pre>
   * TRADE, MARKET_DATA, FX
   * </pre>
   *
   * <code>string eventType = 1;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <pre>
   * Event timestamp
   * </pre>
   *
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * Region (UK, US, JP, CN)
   * </pre>
   *
   * <code>string region = 3;</code>
   * @return The region.
   */
  java.lang.String getRegion();
  /**
   * <pre>
   * Region (UK, US, JP, CN)
   * </pre>
   *
   * <code>string region = 3;</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <pre>
   * For linking multi-stream events
   * </pre>
   *
   * <code>string correlationId = 4;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <pre>
   * For linking multi-stream events
   * </pre>
   *
   * <code>string correlationId = 4;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <pre>
   * serialized TradeEvent, MarketDataEvent, or FxRateEvent
   * </pre>
   *
   * <code>bytes payload = 5;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
