// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package org.jaiswarsecurities.iris.proto;

public interface FxRateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iris.FxRateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ISO code (e.g., USD)
   * </pre>
   *
   * <code>string fromCurrency = 1;</code>
   * @return The fromCurrency.
   */
  java.lang.String getFromCurrency();
  /**
   * <pre>
   * ISO code (e.g., USD)
   * </pre>
   *
   * <code>string fromCurrency = 1;</code>
   * @return The bytes for fromCurrency.
   */
  com.google.protobuf.ByteString
      getFromCurrencyBytes();

  /**
   * <pre>
   * ISO code (e.g., JPY)
   * </pre>
   *
   * <code>string toCurrency = 2;</code>
   * @return The toCurrency.
   */
  java.lang.String getToCurrency();
  /**
   * <pre>
   * ISO code (e.g., JPY)
   * </pre>
   *
   * <code>string toCurrency = 2;</code>
   * @return The bytes for toCurrency.
   */
  com.google.protobuf.ByteString
      getToCurrencyBytes();

  /**
   * <code>double rate = 3;</code>
   * @return The rate.
   */
  double getRate();

  /**
   * <pre>
   * FX bid
   * </pre>
   *
   * <code>double bid = 4;</code>
   * @return The bid.
   */
  double getBid();

  /**
   * <pre>
   * FX ask
   * </pre>
   *
   * <code>double ask = 5;</code>
   * @return The ask.
   */
  double getAsk();

  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * Feed provider (e.g., EBS, Refinitiv)
   * </pre>
   *
   * <code>string source = 7;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <pre>
   * Feed provider (e.g., EBS, Refinitiv)
   * </pre>
   *
   * <code>string source = 7;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();
}
