// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package org.jaiswarsecurities.iris.proto;

/**
 * <pre>
 * ---- FX Rate Event ----
 * </pre>
 *
 * Protobuf type {@code iris.FxRateEvent}
 */
public final class FxRateEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:iris.FxRateEvent)
    FxRateEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FxRateEvent.newBuilder() to construct.
  private FxRateEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FxRateEvent() {
    fromCurrency_ = "";
    toCurrency_ = "";
    source_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FxRateEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_FxRateEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_FxRateEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jaiswarsecurities.iris.proto.FxRateEvent.class, org.jaiswarsecurities.iris.proto.FxRateEvent.Builder.class);
  }

  public static final int FROMCURRENCY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fromCurrency_ = "";
  /**
   * <pre>
   * ISO code (e.g., USD)
   * </pre>
   *
   * <code>string fromCurrency = 1;</code>
   * @return The fromCurrency.
   */
  @java.lang.Override
  public java.lang.String getFromCurrency() {
    java.lang.Object ref = fromCurrency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromCurrency_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ISO code (e.g., USD)
   * </pre>
   *
   * <code>string fromCurrency = 1;</code>
   * @return The bytes for fromCurrency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromCurrencyBytes() {
    java.lang.Object ref = fromCurrency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromCurrency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOCURRENCY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object toCurrency_ = "";
  /**
   * <pre>
   * ISO code (e.g., JPY)
   * </pre>
   *
   * <code>string toCurrency = 2;</code>
   * @return The toCurrency.
   */
  @java.lang.Override
  public java.lang.String getToCurrency() {
    java.lang.Object ref = toCurrency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toCurrency_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ISO code (e.g., JPY)
   * </pre>
   *
   * <code>string toCurrency = 2;</code>
   * @return The bytes for toCurrency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToCurrencyBytes() {
    java.lang.Object ref = toCurrency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toCurrency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RATE_FIELD_NUMBER = 3;
  private double rate_ = 0D;
  /**
   * <code>double rate = 3;</code>
   * @return The rate.
   */
  @java.lang.Override
  public double getRate() {
    return rate_;
  }

  public static final int BID_FIELD_NUMBER = 4;
  private double bid_ = 0D;
  /**
   * <pre>
   * FX bid
   * </pre>
   *
   * <code>double bid = 4;</code>
   * @return The bid.
   */
  @java.lang.Override
  public double getBid() {
    return bid_;
  }

  public static final int ASK_FIELD_NUMBER = 5;
  private double ask_ = 0D;
  /**
   * <pre>
   * FX ask
   * </pre>
   *
   * <code>double ask = 5;</code>
   * @return The ask.
   */
  @java.lang.Override
  public double getAsk() {
    return ask_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int SOURCE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object source_ = "";
  /**
   * <pre>
   * Feed provider (e.g., EBS, Refinitiv)
   * </pre>
   *
   * <code>string source = 7;</code>
   * @return The source.
   */
  @java.lang.Override
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Feed provider (e.g., EBS, Refinitiv)
   * </pre>
   *
   * <code>string source = 7;</code>
   * @return The bytes for source.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromCurrency_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromCurrency_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toCurrency_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, toCurrency_);
    }
    if (java.lang.Double.doubleToRawLongBits(rate_) != 0) {
      output.writeDouble(3, rate_);
    }
    if (java.lang.Double.doubleToRawLongBits(bid_) != 0) {
      output.writeDouble(4, bid_);
    }
    if (java.lang.Double.doubleToRawLongBits(ask_) != 0) {
      output.writeDouble(5, ask_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(6, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(source_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, source_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromCurrency_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromCurrency_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toCurrency_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, toCurrency_);
    }
    if (java.lang.Double.doubleToRawLongBits(rate_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, rate_);
    }
    if (java.lang.Double.doubleToRawLongBits(bid_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, bid_);
    }
    if (java.lang.Double.doubleToRawLongBits(ask_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, ask_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(source_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, source_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.jaiswarsecurities.iris.proto.FxRateEvent)) {
      return super.equals(obj);
    }
    org.jaiswarsecurities.iris.proto.FxRateEvent other = (org.jaiswarsecurities.iris.proto.FxRateEvent) obj;

    if (!getFromCurrency()
        .equals(other.getFromCurrency())) return false;
    if (!getToCurrency()
        .equals(other.getToCurrency())) return false;
    if (java.lang.Double.doubleToLongBits(getRate())
        != java.lang.Double.doubleToLongBits(
            other.getRate())) return false;
    if (java.lang.Double.doubleToLongBits(getBid())
        != java.lang.Double.doubleToLongBits(
            other.getBid())) return false;
    if (java.lang.Double.doubleToLongBits(getAsk())
        != java.lang.Double.doubleToLongBits(
            other.getAsk())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getSource()
        .equals(other.getSource())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROMCURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getFromCurrency().hashCode();
    hash = (37 * hash) + TOCURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getToCurrency().hashCode();
    hash = (37 * hash) + RATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRate()));
    hash = (37 * hash) + BID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBid()));
    hash = (37 * hash) + ASK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAsk()));
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jaiswarsecurities.iris.proto.FxRateEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.jaiswarsecurities.iris.proto.FxRateEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ---- FX Rate Event ----
   * </pre>
   *
   * Protobuf type {@code iris.FxRateEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iris.FxRateEvent)
      org.jaiswarsecurities.iris.proto.FxRateEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_FxRateEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_FxRateEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jaiswarsecurities.iris.proto.FxRateEvent.class, org.jaiswarsecurities.iris.proto.FxRateEvent.Builder.class);
    }

    // Construct using org.jaiswarsecurities.iris.proto.FxRateEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fromCurrency_ = "";
      toCurrency_ = "";
      rate_ = 0D;
      bid_ = 0D;
      ask_ = 0D;
      timestamp_ = 0L;
      source_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_FxRateEvent_descriptor;
    }

    @java.lang.Override
    public org.jaiswarsecurities.iris.proto.FxRateEvent getDefaultInstanceForType() {
      return org.jaiswarsecurities.iris.proto.FxRateEvent.getDefaultInstance();
    }

    @java.lang.Override
    public org.jaiswarsecurities.iris.proto.FxRateEvent build() {
      org.jaiswarsecurities.iris.proto.FxRateEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.jaiswarsecurities.iris.proto.FxRateEvent buildPartial() {
      org.jaiswarsecurities.iris.proto.FxRateEvent result = new org.jaiswarsecurities.iris.proto.FxRateEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.jaiswarsecurities.iris.proto.FxRateEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fromCurrency_ = fromCurrency_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.toCurrency_ = toCurrency_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rate_ = rate_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.bid_ = bid_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.ask_ = ask_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.source_ = source_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.jaiswarsecurities.iris.proto.FxRateEvent) {
        return mergeFrom((org.jaiswarsecurities.iris.proto.FxRateEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jaiswarsecurities.iris.proto.FxRateEvent other) {
      if (other == org.jaiswarsecurities.iris.proto.FxRateEvent.getDefaultInstance()) return this;
      if (!other.getFromCurrency().isEmpty()) {
        fromCurrency_ = other.fromCurrency_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getToCurrency().isEmpty()) {
        toCurrency_ = other.toCurrency_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getRate() != 0D) {
        setRate(other.getRate());
      }
      if (other.getBid() != 0D) {
        setBid(other.getBid());
      }
      if (other.getAsk() != 0D) {
        setAsk(other.getAsk());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              fromCurrency_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              toCurrency_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              rate_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              bid_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              ask_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 48: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              source_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object fromCurrency_ = "";
    /**
     * <pre>
     * ISO code (e.g., USD)
     * </pre>
     *
     * <code>string fromCurrency = 1;</code>
     * @return The fromCurrency.
     */
    public java.lang.String getFromCurrency() {
      java.lang.Object ref = fromCurrency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromCurrency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ISO code (e.g., USD)
     * </pre>
     *
     * <code>string fromCurrency = 1;</code>
     * @return The bytes for fromCurrency.
     */
    public com.google.protobuf.ByteString
        getFromCurrencyBytes() {
      java.lang.Object ref = fromCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ISO code (e.g., USD)
     * </pre>
     *
     * <code>string fromCurrency = 1;</code>
     * @param value The fromCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setFromCurrency(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fromCurrency_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISO code (e.g., USD)
     * </pre>
     *
     * <code>string fromCurrency = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromCurrency() {
      fromCurrency_ = getDefaultInstance().getFromCurrency();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISO code (e.g., USD)
     * </pre>
     *
     * <code>string fromCurrency = 1;</code>
     * @param value The bytes for fromCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setFromCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fromCurrency_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object toCurrency_ = "";
    /**
     * <pre>
     * ISO code (e.g., JPY)
     * </pre>
     *
     * <code>string toCurrency = 2;</code>
     * @return The toCurrency.
     */
    public java.lang.String getToCurrency() {
      java.lang.Object ref = toCurrency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toCurrency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ISO code (e.g., JPY)
     * </pre>
     *
     * <code>string toCurrency = 2;</code>
     * @return The bytes for toCurrency.
     */
    public com.google.protobuf.ByteString
        getToCurrencyBytes() {
      java.lang.Object ref = toCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ISO code (e.g., JPY)
     * </pre>
     *
     * <code>string toCurrency = 2;</code>
     * @param value The toCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setToCurrency(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      toCurrency_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISO code (e.g., JPY)
     * </pre>
     *
     * <code>string toCurrency = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearToCurrency() {
      toCurrency_ = getDefaultInstance().getToCurrency();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISO code (e.g., JPY)
     * </pre>
     *
     * <code>string toCurrency = 2;</code>
     * @param value The bytes for toCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setToCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      toCurrency_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double rate_ ;
    /**
     * <code>double rate = 3;</code>
     * @return The rate.
     */
    @java.lang.Override
    public double getRate() {
      return rate_;
    }
    /**
     * <code>double rate = 3;</code>
     * @param value The rate to set.
     * @return This builder for chaining.
     */
    public Builder setRate(double value) {
      
      rate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double rate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rate_ = 0D;
      onChanged();
      return this;
    }

    private double bid_ ;
    /**
     * <pre>
     * FX bid
     * </pre>
     *
     * <code>double bid = 4;</code>
     * @return The bid.
     */
    @java.lang.Override
    public double getBid() {
      return bid_;
    }
    /**
     * <pre>
     * FX bid
     * </pre>
     *
     * <code>double bid = 4;</code>
     * @param value The bid to set.
     * @return This builder for chaining.
     */
    public Builder setBid(double value) {
      
      bid_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * FX bid
     * </pre>
     *
     * <code>double bid = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBid() {
      bitField0_ = (bitField0_ & ~0x00000008);
      bid_ = 0D;
      onChanged();
      return this;
    }

    private double ask_ ;
    /**
     * <pre>
     * FX ask
     * </pre>
     *
     * <code>double ask = 5;</code>
     * @return The ask.
     */
    @java.lang.Override
    public double getAsk() {
      return ask_;
    }
    /**
     * <pre>
     * FX ask
     * </pre>
     *
     * <code>double ask = 5;</code>
     * @param value The ask to set.
     * @return This builder for chaining.
     */
    public Builder setAsk(double value) {
      
      ask_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * FX ask
     * </pre>
     *
     * <code>double ask = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsk() {
      bitField0_ = (bitField0_ & ~0x00000010);
      ask_ = 0D;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object source_ = "";
    /**
     * <pre>
     * Feed provider (e.g., EBS, Refinitiv)
     * </pre>
     *
     * <code>string source = 7;</code>
     * @return The source.
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Feed provider (e.g., EBS, Refinitiv)
     * </pre>
     *
     * <code>string source = 7;</code>
     * @return The bytes for source.
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Feed provider (e.g., EBS, Refinitiv)
     * </pre>
     *
     * <code>string source = 7;</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      source_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Feed provider (e.g., EBS, Refinitiv)
     * </pre>
     *
     * <code>string source = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      source_ = getDefaultInstance().getSource();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Feed provider (e.g., EBS, Refinitiv)
     * </pre>
     *
     * <code>string source = 7;</code>
     * @param value The bytes for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      source_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:iris.FxRateEvent)
  }

  // @@protoc_insertion_point(class_scope:iris.FxRateEvent)
  private static final org.jaiswarsecurities.iris.proto.FxRateEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.jaiswarsecurities.iris.proto.FxRateEvent();
  }

  public static org.jaiswarsecurities.iris.proto.FxRateEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FxRateEvent>
      PARSER = new com.google.protobuf.AbstractParser<FxRateEvent>() {
    @java.lang.Override
    public FxRateEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FxRateEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FxRateEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.jaiswarsecurities.iris.proto.FxRateEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

