// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package org.jaiswarsecurities.iris.proto;

public final class IrisEvents {
  private IrisEvents() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iris_TradeEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iris_TradeEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iris_MarketDataEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iris_MarketDataEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iris_FxRateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iris_FxRateEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iris_ChipmunkRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iris_ChipmunkRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\niris.proto\022\004iris\"\243\002\n\nTradeEvent\022\017\n\007tra" +
      "deId\030\001 \001(\t\022\017\n\007orderId\030\002 \001(\t\022\022\n\ninstrumen" +
      "t\030\003 \001(\t\022\017\n\007account\030\004 \001(\t\022\024\n\014counterparty" +
      "\030\005 \001(\t\022\020\n\010quantity\030\006 \001(\001\022\r\n\005price\030\007 \001(\001\022" +
      "\014\n\004side\030\010 \001(\t\022\r\n\005venue\030\t \001(\t\022\026\n\016tradeTim" +
      "estamp\030\n \001(\003\022\016\n\006status\030\013 \001(\t\022\024\n\014regulato" +
      "ryId\030\014 \001(\t\022\020\n\010traderId\030\r \001(\t\022\023\n\013strategy" +
      "Tag\030\016 \001(\t\022\025\n\rcorrelationId\030\017 \001(\t\"\252\001\n\017Mar" +
      "ketDataEvent\022\022\n\ninstrument\030\001 \001(\t\022\013\n\003bid\030" +
      "\002 \001(\001\022\013\n\003ask\030\003 \001(\001\022\021\n\tlastPrice\030\004 \001(\001\022\017\n" +
      "\007bidSize\030\005 \001(\001\022\017\n\007askSize\030\006 \001(\001\022\021\n\ttimes" +
      "tamp\030\007 \001(\003\022\r\n\005venue\030\010 \001(\t\022\022\n\nsourceFeed\030" +
      "\t \001(\t\"\202\001\n\013FxRateEvent\022\024\n\014fromCurrency\030\001 " +
      "\001(\t\022\022\n\ntoCurrency\030\002 \001(\t\022\014\n\004rate\030\003 \001(\001\022\013\n" +
      "\003bid\030\004 \001(\001\022\013\n\003ask\030\005 \001(\001\022\021\n\ttimestamp\030\006 \001" +
      "(\003\022\016\n\006source\030\007 \001(\t\"n\n\016ChipmunkRecord\022\021\n\t" +
      "eventType\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\003\022\016\n\006re" +
      "gion\030\003 \001(\t\022\025\n\rcorrelationId\030\004 \001(\t\022\017\n\007pay" +
      "load\030\005 \001(\014B0\n org.jaiswarsecurities.iris" +
      ".protoB\nIrisEventsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_iris_TradeEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_iris_TradeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iris_TradeEvent_descriptor,
        new java.lang.String[] { "TradeId", "OrderId", "Instrument", "Account", "Counterparty", "Quantity", "Price", "Side", "Venue", "TradeTimestamp", "Status", "RegulatoryId", "TraderId", "StrategyTag", "CorrelationId", });
    internal_static_iris_MarketDataEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_iris_MarketDataEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iris_MarketDataEvent_descriptor,
        new java.lang.String[] { "Instrument", "Bid", "Ask", "LastPrice", "BidSize", "AskSize", "Timestamp", "Venue", "SourceFeed", });
    internal_static_iris_FxRateEvent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_iris_FxRateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iris_FxRateEvent_descriptor,
        new java.lang.String[] { "FromCurrency", "ToCurrency", "Rate", "Bid", "Ask", "Timestamp", "Source", });
    internal_static_iris_ChipmunkRecord_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_iris_ChipmunkRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iris_ChipmunkRecord_descriptor,
        new java.lang.String[] { "EventType", "Timestamp", "Region", "CorrelationId", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
