// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package org.jaiswarsecurities.iris.proto;

public interface MarketDataEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iris.MarketDataEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ISIN, RIC, or symbol
   * </pre>
   *
   * <code>string instrument = 1;</code>
   * @return The instrument.
   */
  java.lang.String getInstrument();
  /**
   * <pre>
   * ISIN, RIC, or symbol
   * </pre>
   *
   * <code>string instrument = 1;</code>
   * @return The bytes for instrument.
   */
  com.google.protobuf.ByteString
      getInstrumentBytes();

  /**
   * <code>double bid = 2;</code>
   * @return The bid.
   */
  double getBid();

  /**
   * <code>double ask = 3;</code>
   * @return The ask.
   */
  double getAsk();

  /**
   * <code>double lastPrice = 4;</code>
   * @return The lastPrice.
   */
  double getLastPrice();

  /**
   * <code>double bidSize = 5;</code>
   * @return The bidSize.
   */
  double getBidSize();

  /**
   * <code>double askSize = 6;</code>
   * @return The askSize.
   */
  double getAskSize();

  /**
   * <pre>
   * Event-time in market feed
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * Market or exchange
   * </pre>
   *
   * <code>string venue = 8;</code>
   * @return The venue.
   */
  java.lang.String getVenue();
  /**
   * <pre>
   * Market or exchange
   * </pre>
   *
   * <code>string venue = 8;</code>
   * @return The bytes for venue.
   */
  com.google.protobuf.ByteString
      getVenueBytes();

  /**
   * <pre>
   * e.g., Bloomberg, Reuters, DirectFeed
   * </pre>
   *
   * <code>string sourceFeed = 9;</code>
   * @return The sourceFeed.
   */
  java.lang.String getSourceFeed();
  /**
   * <pre>
   * e.g., Bloomberg, Reuters, DirectFeed
   * </pre>
   *
   * <code>string sourceFeed = 9;</code>
   * @return The bytes for sourceFeed.
   */
  com.google.protobuf.ByteString
      getSourceFeedBytes();
}
