// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package org.jaiswarsecurities.iris.proto;

/**
 * <pre>
 * ---- Market Data Event ----
 * </pre>
 *
 * Protobuf type {@code iris.MarketDataEvent}
 */
public final class MarketDataEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:iris.MarketDataEvent)
    MarketDataEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MarketDataEvent.newBuilder() to construct.
  private MarketDataEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MarketDataEvent() {
    instrument_ = "";
    venue_ = "";
    sourceFeed_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MarketDataEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_MarketDataEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_MarketDataEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jaiswarsecurities.iris.proto.MarketDataEvent.class, org.jaiswarsecurities.iris.proto.MarketDataEvent.Builder.class);
  }

  public static final int INSTRUMENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object instrument_ = "";
  /**
   * <pre>
   * ISIN, RIC, or symbol
   * </pre>
   *
   * <code>string instrument = 1;</code>
   * @return The instrument.
   */
  @java.lang.Override
  public java.lang.String getInstrument() {
    java.lang.Object ref = instrument_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instrument_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ISIN, RIC, or symbol
   * </pre>
   *
   * <code>string instrument = 1;</code>
   * @return The bytes for instrument.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstrumentBytes() {
    java.lang.Object ref = instrument_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instrument_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BID_FIELD_NUMBER = 2;
  private double bid_ = 0D;
  /**
   * <code>double bid = 2;</code>
   * @return The bid.
   */
  @java.lang.Override
  public double getBid() {
    return bid_;
  }

  public static final int ASK_FIELD_NUMBER = 3;
  private double ask_ = 0D;
  /**
   * <code>double ask = 3;</code>
   * @return The ask.
   */
  @java.lang.Override
  public double getAsk() {
    return ask_;
  }

  public static final int LASTPRICE_FIELD_NUMBER = 4;
  private double lastPrice_ = 0D;
  /**
   * <code>double lastPrice = 4;</code>
   * @return The lastPrice.
   */
  @java.lang.Override
  public double getLastPrice() {
    return lastPrice_;
  }

  public static final int BIDSIZE_FIELD_NUMBER = 5;
  private double bidSize_ = 0D;
  /**
   * <code>double bidSize = 5;</code>
   * @return The bidSize.
   */
  @java.lang.Override
  public double getBidSize() {
    return bidSize_;
  }

  public static final int ASKSIZE_FIELD_NUMBER = 6;
  private double askSize_ = 0D;
  /**
   * <code>double askSize = 6;</code>
   * @return The askSize.
   */
  @java.lang.Override
  public double getAskSize() {
    return askSize_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * Event-time in market feed
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int VENUE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object venue_ = "";
  /**
   * <pre>
   * Market or exchange
   * </pre>
   *
   * <code>string venue = 8;</code>
   * @return The venue.
   */
  @java.lang.Override
  public java.lang.String getVenue() {
    java.lang.Object ref = venue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      venue_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Market or exchange
   * </pre>
   *
   * <code>string venue = 8;</code>
   * @return The bytes for venue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVenueBytes() {
    java.lang.Object ref = venue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      venue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEFEED_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceFeed_ = "";
  /**
   * <pre>
   * e.g., Bloomberg, Reuters, DirectFeed
   * </pre>
   *
   * <code>string sourceFeed = 9;</code>
   * @return The sourceFeed.
   */
  @java.lang.Override
  public java.lang.String getSourceFeed() {
    java.lang.Object ref = sourceFeed_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceFeed_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g., Bloomberg, Reuters, DirectFeed
   * </pre>
   *
   * <code>string sourceFeed = 9;</code>
   * @return The bytes for sourceFeed.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceFeedBytes() {
    java.lang.Object ref = sourceFeed_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceFeed_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instrument_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, instrument_);
    }
    if (java.lang.Double.doubleToRawLongBits(bid_) != 0) {
      output.writeDouble(2, bid_);
    }
    if (java.lang.Double.doubleToRawLongBits(ask_) != 0) {
      output.writeDouble(3, ask_);
    }
    if (java.lang.Double.doubleToRawLongBits(lastPrice_) != 0) {
      output.writeDouble(4, lastPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(bidSize_) != 0) {
      output.writeDouble(5, bidSize_);
    }
    if (java.lang.Double.doubleToRawLongBits(askSize_) != 0) {
      output.writeDouble(6, askSize_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(venue_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, venue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceFeed_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, sourceFeed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instrument_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, instrument_);
    }
    if (java.lang.Double.doubleToRawLongBits(bid_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, bid_);
    }
    if (java.lang.Double.doubleToRawLongBits(ask_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, ask_);
    }
    if (java.lang.Double.doubleToRawLongBits(lastPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, lastPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(bidSize_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, bidSize_);
    }
    if (java.lang.Double.doubleToRawLongBits(askSize_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, askSize_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(venue_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, venue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceFeed_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, sourceFeed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.jaiswarsecurities.iris.proto.MarketDataEvent)) {
      return super.equals(obj);
    }
    org.jaiswarsecurities.iris.proto.MarketDataEvent other = (org.jaiswarsecurities.iris.proto.MarketDataEvent) obj;

    if (!getInstrument()
        .equals(other.getInstrument())) return false;
    if (java.lang.Double.doubleToLongBits(getBid())
        != java.lang.Double.doubleToLongBits(
            other.getBid())) return false;
    if (java.lang.Double.doubleToLongBits(getAsk())
        != java.lang.Double.doubleToLongBits(
            other.getAsk())) return false;
    if (java.lang.Double.doubleToLongBits(getLastPrice())
        != java.lang.Double.doubleToLongBits(
            other.getLastPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getBidSize())
        != java.lang.Double.doubleToLongBits(
            other.getBidSize())) return false;
    if (java.lang.Double.doubleToLongBits(getAskSize())
        != java.lang.Double.doubleToLongBits(
            other.getAskSize())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getVenue()
        .equals(other.getVenue())) return false;
    if (!getSourceFeed()
        .equals(other.getSourceFeed())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
    hash = (53 * hash) + getInstrument().hashCode();
    hash = (37 * hash) + BID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBid()));
    hash = (37 * hash) + ASK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAsk()));
    hash = (37 * hash) + LASTPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLastPrice()));
    hash = (37 * hash) + BIDSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBidSize()));
    hash = (37 * hash) + ASKSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAskSize()));
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + VENUE_FIELD_NUMBER;
    hash = (53 * hash) + getVenue().hashCode();
    hash = (37 * hash) + SOURCEFEED_FIELD_NUMBER;
    hash = (53 * hash) + getSourceFeed().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jaiswarsecurities.iris.proto.MarketDataEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.jaiswarsecurities.iris.proto.MarketDataEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ---- Market Data Event ----
   * </pre>
   *
   * Protobuf type {@code iris.MarketDataEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iris.MarketDataEvent)
      org.jaiswarsecurities.iris.proto.MarketDataEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_MarketDataEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_MarketDataEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jaiswarsecurities.iris.proto.MarketDataEvent.class, org.jaiswarsecurities.iris.proto.MarketDataEvent.Builder.class);
    }

    // Construct using org.jaiswarsecurities.iris.proto.MarketDataEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      instrument_ = "";
      bid_ = 0D;
      ask_ = 0D;
      lastPrice_ = 0D;
      bidSize_ = 0D;
      askSize_ = 0D;
      timestamp_ = 0L;
      venue_ = "";
      sourceFeed_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_MarketDataEvent_descriptor;
    }

    @java.lang.Override
    public org.jaiswarsecurities.iris.proto.MarketDataEvent getDefaultInstanceForType() {
      return org.jaiswarsecurities.iris.proto.MarketDataEvent.getDefaultInstance();
    }

    @java.lang.Override
    public org.jaiswarsecurities.iris.proto.MarketDataEvent build() {
      org.jaiswarsecurities.iris.proto.MarketDataEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.jaiswarsecurities.iris.proto.MarketDataEvent buildPartial() {
      org.jaiswarsecurities.iris.proto.MarketDataEvent result = new org.jaiswarsecurities.iris.proto.MarketDataEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.jaiswarsecurities.iris.proto.MarketDataEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.instrument_ = instrument_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bid_ = bid_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ask_ = ask_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lastPrice_ = lastPrice_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.bidSize_ = bidSize_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.askSize_ = askSize_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.venue_ = venue_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.sourceFeed_ = sourceFeed_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.jaiswarsecurities.iris.proto.MarketDataEvent) {
        return mergeFrom((org.jaiswarsecurities.iris.proto.MarketDataEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jaiswarsecurities.iris.proto.MarketDataEvent other) {
      if (other == org.jaiswarsecurities.iris.proto.MarketDataEvent.getDefaultInstance()) return this;
      if (!other.getInstrument().isEmpty()) {
        instrument_ = other.instrument_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getBid() != 0D) {
        setBid(other.getBid());
      }
      if (other.getAsk() != 0D) {
        setAsk(other.getAsk());
      }
      if (other.getLastPrice() != 0D) {
        setLastPrice(other.getLastPrice());
      }
      if (other.getBidSize() != 0D) {
        setBidSize(other.getBidSize());
      }
      if (other.getAskSize() != 0D) {
        setAskSize(other.getAskSize());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getVenue().isEmpty()) {
        venue_ = other.venue_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getSourceFeed().isEmpty()) {
        sourceFeed_ = other.sourceFeed_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              instrument_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              bid_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              ask_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              lastPrice_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              bidSize_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 49: {
              askSize_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 56: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              venue_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              sourceFeed_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object instrument_ = "";
    /**
     * <pre>
     * ISIN, RIC, or symbol
     * </pre>
     *
     * <code>string instrument = 1;</code>
     * @return The instrument.
     */
    public java.lang.String getInstrument() {
      java.lang.Object ref = instrument_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instrument_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ISIN, RIC, or symbol
     * </pre>
     *
     * <code>string instrument = 1;</code>
     * @return The bytes for instrument.
     */
    public com.google.protobuf.ByteString
        getInstrumentBytes() {
      java.lang.Object ref = instrument_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ISIN, RIC, or symbol
     * </pre>
     *
     * <code>string instrument = 1;</code>
     * @param value The instrument to set.
     * @return This builder for chaining.
     */
    public Builder setInstrument(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      instrument_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISIN, RIC, or symbol
     * </pre>
     *
     * <code>string instrument = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInstrument() {
      instrument_ = getDefaultInstance().getInstrument();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISIN, RIC, or symbol
     * </pre>
     *
     * <code>string instrument = 1;</code>
     * @param value The bytes for instrument to set.
     * @return This builder for chaining.
     */
    public Builder setInstrumentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      instrument_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double bid_ ;
    /**
     * <code>double bid = 2;</code>
     * @return The bid.
     */
    @java.lang.Override
    public double getBid() {
      return bid_;
    }
    /**
     * <code>double bid = 2;</code>
     * @param value The bid to set.
     * @return This builder for chaining.
     */
    public Builder setBid(double value) {
      
      bid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double bid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bid_ = 0D;
      onChanged();
      return this;
    }

    private double ask_ ;
    /**
     * <code>double ask = 3;</code>
     * @return The ask.
     */
    @java.lang.Override
    public double getAsk() {
      return ask_;
    }
    /**
     * <code>double ask = 3;</code>
     * @param value The ask to set.
     * @return This builder for chaining.
     */
    public Builder setAsk(double value) {
      
      ask_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double ask = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsk() {
      bitField0_ = (bitField0_ & ~0x00000004);
      ask_ = 0D;
      onChanged();
      return this;
    }

    private double lastPrice_ ;
    /**
     * <code>double lastPrice = 4;</code>
     * @return The lastPrice.
     */
    @java.lang.Override
    public double getLastPrice() {
      return lastPrice_;
    }
    /**
     * <code>double lastPrice = 4;</code>
     * @param value The lastPrice to set.
     * @return This builder for chaining.
     */
    public Builder setLastPrice(double value) {
      
      lastPrice_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double lastPrice = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastPrice() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lastPrice_ = 0D;
      onChanged();
      return this;
    }

    private double bidSize_ ;
    /**
     * <code>double bidSize = 5;</code>
     * @return The bidSize.
     */
    @java.lang.Override
    public double getBidSize() {
      return bidSize_;
    }
    /**
     * <code>double bidSize = 5;</code>
     * @param value The bidSize to set.
     * @return This builder for chaining.
     */
    public Builder setBidSize(double value) {
      
      bidSize_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double bidSize = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBidSize() {
      bitField0_ = (bitField0_ & ~0x00000010);
      bidSize_ = 0D;
      onChanged();
      return this;
    }

    private double askSize_ ;
    /**
     * <code>double askSize = 6;</code>
     * @return The askSize.
     */
    @java.lang.Override
    public double getAskSize() {
      return askSize_;
    }
    /**
     * <code>double askSize = 6;</code>
     * @param value The askSize to set.
     * @return This builder for chaining.
     */
    public Builder setAskSize(double value) {
      
      askSize_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double askSize = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAskSize() {
      bitField0_ = (bitField0_ & ~0x00000020);
      askSize_ = 0D;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * Event-time in market feed
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Event-time in market feed
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Event-time in market feed
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object venue_ = "";
    /**
     * <pre>
     * Market or exchange
     * </pre>
     *
     * <code>string venue = 8;</code>
     * @return The venue.
     */
    public java.lang.String getVenue() {
      java.lang.Object ref = venue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        venue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Market or exchange
     * </pre>
     *
     * <code>string venue = 8;</code>
     * @return The bytes for venue.
     */
    public com.google.protobuf.ByteString
        getVenueBytes() {
      java.lang.Object ref = venue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        venue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Market or exchange
     * </pre>
     *
     * <code>string venue = 8;</code>
     * @param value The venue to set.
     * @return This builder for chaining.
     */
    public Builder setVenue(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      venue_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Market or exchange
     * </pre>
     *
     * <code>string venue = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearVenue() {
      venue_ = getDefaultInstance().getVenue();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Market or exchange
     * </pre>
     *
     * <code>string venue = 8;</code>
     * @param value The bytes for venue to set.
     * @return This builder for chaining.
     */
    public Builder setVenueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      venue_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object sourceFeed_ = "";
    /**
     * <pre>
     * e.g., Bloomberg, Reuters, DirectFeed
     * </pre>
     *
     * <code>string sourceFeed = 9;</code>
     * @return The sourceFeed.
     */
    public java.lang.String getSourceFeed() {
      java.lang.Object ref = sourceFeed_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceFeed_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g., Bloomberg, Reuters, DirectFeed
     * </pre>
     *
     * <code>string sourceFeed = 9;</code>
     * @return The bytes for sourceFeed.
     */
    public com.google.protobuf.ByteString
        getSourceFeedBytes() {
      java.lang.Object ref = sourceFeed_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceFeed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g., Bloomberg, Reuters, DirectFeed
     * </pre>
     *
     * <code>string sourceFeed = 9;</code>
     * @param value The sourceFeed to set.
     * @return This builder for chaining.
     */
    public Builder setSourceFeed(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceFeed_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., Bloomberg, Reuters, DirectFeed
     * </pre>
     *
     * <code>string sourceFeed = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceFeed() {
      sourceFeed_ = getDefaultInstance().getSourceFeed();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., Bloomberg, Reuters, DirectFeed
     * </pre>
     *
     * <code>string sourceFeed = 9;</code>
     * @param value The bytes for sourceFeed to set.
     * @return This builder for chaining.
     */
    public Builder setSourceFeedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceFeed_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:iris.MarketDataEvent)
  }

  // @@protoc_insertion_point(class_scope:iris.MarketDataEvent)
  private static final org.jaiswarsecurities.iris.proto.MarketDataEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.jaiswarsecurities.iris.proto.MarketDataEvent();
  }

  public static org.jaiswarsecurities.iris.proto.MarketDataEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MarketDataEvent>
      PARSER = new com.google.protobuf.AbstractParser<MarketDataEvent>() {
    @java.lang.Override
    public MarketDataEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MarketDataEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MarketDataEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.jaiswarsecurities.iris.proto.MarketDataEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

