// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris.proto

package org.jaiswarsecurities.iris.proto;

/**
 * <pre>
 * ---- Trade Event ----
 * </pre>
 *
 * Protobuf type {@code iris.TradeEvent}
 */
public final class TradeEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:iris.TradeEvent)
    TradeEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TradeEvent.newBuilder() to construct.
  private TradeEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TradeEvent() {
    tradeId_ = "";
    orderId_ = "";
    instrument_ = "";
    account_ = "";
    counterparty_ = "";
    side_ = "";
    venue_ = "";
    status_ = "";
    regulatoryId_ = "";
    traderId_ = "";
    strategyTag_ = "";
    correlationId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TradeEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_TradeEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_TradeEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jaiswarsecurities.iris.proto.TradeEvent.class, org.jaiswarsecurities.iris.proto.TradeEvent.Builder.class);
  }

  public static final int TRADEID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tradeId_ = "";
  /**
   * <pre>
   * Unique trade ID (per venue/broker)
   * </pre>
   *
   * <code>string tradeId = 1;</code>
   * @return The tradeId.
   */
  @java.lang.Override
  public java.lang.String getTradeId() {
    java.lang.Object ref = tradeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tradeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique trade ID (per venue/broker)
   * </pre>
   *
   * <code>string tradeId = 1;</code>
   * @return The bytes for tradeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTradeIdBytes() {
    java.lang.Object ref = tradeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tradeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDERID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object orderId_ = "";
  /**
   * <pre>
   * Parent order reference
   * </pre>
   *
   * <code>string orderId = 2;</code>
   * @return The orderId.
   */
  @java.lang.Override
  public java.lang.String getOrderId() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Parent order reference
   * </pre>
   *
   * <code>string orderId = 2;</code>
   * @return The bytes for orderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrderIdBytes() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTRUMENT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object instrument_ = "";
  /**
   * <pre>
   * ISIN, RIC, or symbol
   * </pre>
   *
   * <code>string instrument = 3;</code>
   * @return The instrument.
   */
  @java.lang.Override
  public java.lang.String getInstrument() {
    java.lang.Object ref = instrument_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instrument_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ISIN, RIC, or symbol
   * </pre>
   *
   * <code>string instrument = 3;</code>
   * @return The bytes for instrument.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstrumentBytes() {
    java.lang.Object ref = instrument_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instrument_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNT_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object account_ = "";
  /**
   * <pre>
   * Trading account ID
   * </pre>
   *
   * <code>string account = 4;</code>
   * @return The account.
   */
  @java.lang.Override
  public java.lang.String getAccount() {
    java.lang.Object ref = account_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      account_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Trading account ID
   * </pre>
   *
   * <code>string account = 4;</code>
   * @return The bytes for account.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccountBytes() {
    java.lang.Object ref = account_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      account_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNTERPARTY_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object counterparty_ = "";
  /**
   * <pre>
   * Broker/Dealer/Exchange
   * </pre>
   *
   * <code>string counterparty = 5;</code>
   * @return The counterparty.
   */
  @java.lang.Override
  public java.lang.String getCounterparty() {
    java.lang.Object ref = counterparty_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      counterparty_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Broker/Dealer/Exchange
   * </pre>
   *
   * <code>string counterparty = 5;</code>
   * @return The bytes for counterparty.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCounterpartyBytes() {
    java.lang.Object ref = counterparty_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      counterparty_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 6;
  private double quantity_ = 0D;
  /**
   * <pre>
   * Executed quantity
   * </pre>
   *
   * <code>double quantity = 6;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public double getQuantity() {
    return quantity_;
  }

  public static final int PRICE_FIELD_NUMBER = 7;
  private double price_ = 0D;
  /**
   * <pre>
   * Execution price
   * </pre>
   *
   * <code>double price = 7;</code>
   * @return The price.
   */
  @java.lang.Override
  public double getPrice() {
    return price_;
  }

  public static final int SIDE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object side_ = "";
  /**
   * <pre>
   * BUY or SELL
   * </pre>
   *
   * <code>string side = 8;</code>
   * @return The side.
   */
  @java.lang.Override
  public java.lang.String getSide() {
    java.lang.Object ref = side_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      side_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * BUY or SELL
   * </pre>
   *
   * <code>string side = 8;</code>
   * @return The bytes for side.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSideBytes() {
    java.lang.Object ref = side_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      side_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VENUE_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object venue_ = "";
  /**
   * <pre>
   * Market or exchange (e.g., LSE, NYSE)
   * </pre>
   *
   * <code>string venue = 9;</code>
   * @return The venue.
   */
  @java.lang.Override
  public java.lang.String getVenue() {
    java.lang.Object ref = venue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      venue_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Market or exchange (e.g., LSE, NYSE)
   * </pre>
   *
   * <code>string venue = 9;</code>
   * @return The bytes for venue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVenueBytes() {
    java.lang.Object ref = venue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      venue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRADETIMESTAMP_FIELD_NUMBER = 10;
  private long tradeTimestamp_ = 0L;
  /**
   * <pre>
   * Execution timestamp (epoch millis)
   * </pre>
   *
   * <code>int64 tradeTimestamp = 10;</code>
   * @return The tradeTimestamp.
   */
  @java.lang.Override
  public long getTradeTimestamp() {
    return tradeTimestamp_;
  }

  public static final int STATUS_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <pre>
   * NEW, AMEND, CANCEL, FILLED, PARTIALLY_FILLED
   * </pre>
   *
   * <code>string status = 11;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * NEW, AMEND, CANCEL, FILLED, PARTIALLY_FILLED
   * </pre>
   *
   * <code>string status = 11;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REGULATORYID_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object regulatoryId_ = "";
  /**
   * <pre>
   * MiFID / SEC / local trade identifier
   * </pre>
   *
   * <code>string regulatoryId = 12;</code>
   * @return The regulatoryId.
   */
  @java.lang.Override
  public java.lang.String getRegulatoryId() {
    java.lang.Object ref = regulatoryId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      regulatoryId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * MiFID / SEC / local trade identifier
   * </pre>
   *
   * <code>string regulatoryId = 12;</code>
   * @return The bytes for regulatoryId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRegulatoryIdBytes() {
    java.lang.Object ref = regulatoryId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      regulatoryId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRADERID_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traderId_ = "";
  /**
   * <pre>
   * Internal trader reference
   * </pre>
   *
   * <code>string traderId = 13;</code>
   * @return The traderId.
   */
  @java.lang.Override
  public java.lang.String getTraderId() {
    java.lang.Object ref = traderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traderId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Internal trader reference
   * </pre>
   *
   * <code>string traderId = 13;</code>
   * @return The bytes for traderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraderIdBytes() {
    java.lang.Object ref = traderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRATEGYTAG_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private volatile java.lang.Object strategyTag_ = "";
  /**
   * <pre>
   * Algo strategy / manual / HFT
   * </pre>
   *
   * <code>string strategyTag = 14;</code>
   * @return The strategyTag.
   */
  @java.lang.Override
  public java.lang.String getStrategyTag() {
    java.lang.Object ref = strategyTag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      strategyTag_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Algo strategy / manual / HFT
   * </pre>
   *
   * <code>string strategyTag = 14;</code>
   * @return The bytes for strategyTag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStrategyTagBytes() {
    java.lang.Object ref = strategyTag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      strategyTag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CORRELATIONID_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile java.lang.Object correlationId_ = "";
  /**
   * <pre>
   * For linking across events (e.g., parent-child orders)
   * </pre>
   *
   * <code>string correlationId = 15;</code>
   * @return The correlationId.
   */
  @java.lang.Override
  public java.lang.String getCorrelationId() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      correlationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * For linking across events (e.g., parent-child orders)
   * </pre>
   *
   * <code>string correlationId = 15;</code>
   * @return The bytes for correlationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCorrelationIdBytes() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      correlationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tradeId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tradeId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instrument_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, instrument_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(account_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, account_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(counterparty_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, counterparty_);
    }
    if (java.lang.Double.doubleToRawLongBits(quantity_) != 0) {
      output.writeDouble(6, quantity_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      output.writeDouble(7, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(side_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, side_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(venue_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, venue_);
    }
    if (tradeTimestamp_ != 0L) {
      output.writeInt64(10, tradeTimestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(regulatoryId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, regulatoryId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traderId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, traderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(strategyTag_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, strategyTag_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, correlationId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tradeId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tradeId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instrument_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, instrument_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(account_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, account_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(counterparty_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, counterparty_);
    }
    if (java.lang.Double.doubleToRawLongBits(quantity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, quantity_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(side_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, side_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(venue_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, venue_);
    }
    if (tradeTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, tradeTimestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(regulatoryId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, regulatoryId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traderId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, traderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(strategyTag_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, strategyTag_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, correlationId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.jaiswarsecurities.iris.proto.TradeEvent)) {
      return super.equals(obj);
    }
    org.jaiswarsecurities.iris.proto.TradeEvent other = (org.jaiswarsecurities.iris.proto.TradeEvent) obj;

    if (!getTradeId()
        .equals(other.getTradeId())) return false;
    if (!getOrderId()
        .equals(other.getOrderId())) return false;
    if (!getInstrument()
        .equals(other.getInstrument())) return false;
    if (!getAccount()
        .equals(other.getAccount())) return false;
    if (!getCounterparty()
        .equals(other.getCounterparty())) return false;
    if (java.lang.Double.doubleToLongBits(getQuantity())
        != java.lang.Double.doubleToLongBits(
            other.getQuantity())) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (!getSide()
        .equals(other.getSide())) return false;
    if (!getVenue()
        .equals(other.getVenue())) return false;
    if (getTradeTimestamp()
        != other.getTradeTimestamp()) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getRegulatoryId()
        .equals(other.getRegulatoryId())) return false;
    if (!getTraderId()
        .equals(other.getTraderId())) return false;
    if (!getStrategyTag()
        .equals(other.getStrategyTag())) return false;
    if (!getCorrelationId()
        .equals(other.getCorrelationId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRADEID_FIELD_NUMBER;
    hash = (53 * hash) + getTradeId().hashCode();
    hash = (37 * hash) + ORDERID_FIELD_NUMBER;
    hash = (53 * hash) + getOrderId().hashCode();
    hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
    hash = (53 * hash) + getInstrument().hashCode();
    hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAccount().hashCode();
    hash = (37 * hash) + COUNTERPARTY_FIELD_NUMBER;
    hash = (53 * hash) + getCounterparty().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getQuantity()));
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + SIDE_FIELD_NUMBER;
    hash = (53 * hash) + getSide().hashCode();
    hash = (37 * hash) + VENUE_FIELD_NUMBER;
    hash = (53 * hash) + getVenue().hashCode();
    hash = (37 * hash) + TRADETIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTradeTimestamp());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + REGULATORYID_FIELD_NUMBER;
    hash = (53 * hash) + getRegulatoryId().hashCode();
    hash = (37 * hash) + TRADERID_FIELD_NUMBER;
    hash = (53 * hash) + getTraderId().hashCode();
    hash = (37 * hash) + STRATEGYTAG_FIELD_NUMBER;
    hash = (53 * hash) + getStrategyTag().hashCode();
    hash = (37 * hash) + CORRELATIONID_FIELD_NUMBER;
    hash = (53 * hash) + getCorrelationId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.jaiswarsecurities.iris.proto.TradeEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jaiswarsecurities.iris.proto.TradeEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.TradeEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jaiswarsecurities.iris.proto.TradeEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.TradeEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jaiswarsecurities.iris.proto.TradeEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.TradeEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jaiswarsecurities.iris.proto.TradeEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.TradeEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.jaiswarsecurities.iris.proto.TradeEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jaiswarsecurities.iris.proto.TradeEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jaiswarsecurities.iris.proto.TradeEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.jaiswarsecurities.iris.proto.TradeEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ---- Trade Event ----
   * </pre>
   *
   * Protobuf type {@code iris.TradeEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iris.TradeEvent)
      org.jaiswarsecurities.iris.proto.TradeEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_TradeEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_TradeEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jaiswarsecurities.iris.proto.TradeEvent.class, org.jaiswarsecurities.iris.proto.TradeEvent.Builder.class);
    }

    // Construct using org.jaiswarsecurities.iris.proto.TradeEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tradeId_ = "";
      orderId_ = "";
      instrument_ = "";
      account_ = "";
      counterparty_ = "";
      quantity_ = 0D;
      price_ = 0D;
      side_ = "";
      venue_ = "";
      tradeTimestamp_ = 0L;
      status_ = "";
      regulatoryId_ = "";
      traderId_ = "";
      strategyTag_ = "";
      correlationId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.jaiswarsecurities.iris.proto.IrisEvents.internal_static_iris_TradeEvent_descriptor;
    }

    @java.lang.Override
    public org.jaiswarsecurities.iris.proto.TradeEvent getDefaultInstanceForType() {
      return org.jaiswarsecurities.iris.proto.TradeEvent.getDefaultInstance();
    }

    @java.lang.Override
    public org.jaiswarsecurities.iris.proto.TradeEvent build() {
      org.jaiswarsecurities.iris.proto.TradeEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.jaiswarsecurities.iris.proto.TradeEvent buildPartial() {
      org.jaiswarsecurities.iris.proto.TradeEvent result = new org.jaiswarsecurities.iris.proto.TradeEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.jaiswarsecurities.iris.proto.TradeEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tradeId_ = tradeId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.orderId_ = orderId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.instrument_ = instrument_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.account_ = account_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.counterparty_ = counterparty_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.quantity_ = quantity_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.price_ = price_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.side_ = side_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.venue_ = venue_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.tradeTimestamp_ = tradeTimestamp_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.regulatoryId_ = regulatoryId_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.traderId_ = traderId_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.strategyTag_ = strategyTag_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.correlationId_ = correlationId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.jaiswarsecurities.iris.proto.TradeEvent) {
        return mergeFrom((org.jaiswarsecurities.iris.proto.TradeEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jaiswarsecurities.iris.proto.TradeEvent other) {
      if (other == org.jaiswarsecurities.iris.proto.TradeEvent.getDefaultInstance()) return this;
      if (!other.getTradeId().isEmpty()) {
        tradeId_ = other.tradeId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getOrderId().isEmpty()) {
        orderId_ = other.orderId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getInstrument().isEmpty()) {
        instrument_ = other.instrument_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAccount().isEmpty()) {
        account_ = other.account_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getCounterparty().isEmpty()) {
        counterparty_ = other.counterparty_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getQuantity() != 0D) {
        setQuantity(other.getQuantity());
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (!other.getSide().isEmpty()) {
        side_ = other.side_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getVenue().isEmpty()) {
        venue_ = other.venue_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.getTradeTimestamp() != 0L) {
        setTradeTimestamp(other.getTradeTimestamp());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getRegulatoryId().isEmpty()) {
        regulatoryId_ = other.regulatoryId_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (!other.getTraderId().isEmpty()) {
        traderId_ = other.traderId_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (!other.getStrategyTag().isEmpty()) {
        strategyTag_ = other.strategyTag_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      if (!other.getCorrelationId().isEmpty()) {
        correlationId_ = other.correlationId_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tradeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              orderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              instrument_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              account_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              counterparty_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 49: {
              quantity_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 57: {
              price_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 66: {
              side_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              venue_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              tradeTimestamp_ = input.readInt64();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              regulatoryId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              traderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              strategyTag_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 122: {
              correlationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tradeId_ = "";
    /**
     * <pre>
     * Unique trade ID (per venue/broker)
     * </pre>
     *
     * <code>string tradeId = 1;</code>
     * @return The tradeId.
     */
    public java.lang.String getTradeId() {
      java.lang.Object ref = tradeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tradeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique trade ID (per venue/broker)
     * </pre>
     *
     * <code>string tradeId = 1;</code>
     * @return The bytes for tradeId.
     */
    public com.google.protobuf.ByteString
        getTradeIdBytes() {
      java.lang.Object ref = tradeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tradeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique trade ID (per venue/broker)
     * </pre>
     *
     * <code>string tradeId = 1;</code>
     * @param value The tradeId to set.
     * @return This builder for chaining.
     */
    public Builder setTradeId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tradeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique trade ID (per venue/broker)
     * </pre>
     *
     * <code>string tradeId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTradeId() {
      tradeId_ = getDefaultInstance().getTradeId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique trade ID (per venue/broker)
     * </pre>
     *
     * <code>string tradeId = 1;</code>
     * @param value The bytes for tradeId to set.
     * @return This builder for chaining.
     */
    public Builder setTradeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tradeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object orderId_ = "";
    /**
     * <pre>
     * Parent order reference
     * </pre>
     *
     * <code>string orderId = 2;</code>
     * @return The orderId.
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Parent order reference
     * </pre>
     *
     * <code>string orderId = 2;</code>
     * @return The bytes for orderId.
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Parent order reference
     * </pre>
     *
     * <code>string orderId = 2;</code>
     * @param value The orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      orderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Parent order reference
     * </pre>
     *
     * <code>string orderId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderId() {
      orderId_ = getDefaultInstance().getOrderId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Parent order reference
     * </pre>
     *
     * <code>string orderId = 2;</code>
     * @param value The bytes for orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      orderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object instrument_ = "";
    /**
     * <pre>
     * ISIN, RIC, or symbol
     * </pre>
     *
     * <code>string instrument = 3;</code>
     * @return The instrument.
     */
    public java.lang.String getInstrument() {
      java.lang.Object ref = instrument_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instrument_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ISIN, RIC, or symbol
     * </pre>
     *
     * <code>string instrument = 3;</code>
     * @return The bytes for instrument.
     */
    public com.google.protobuf.ByteString
        getInstrumentBytes() {
      java.lang.Object ref = instrument_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ISIN, RIC, or symbol
     * </pre>
     *
     * <code>string instrument = 3;</code>
     * @param value The instrument to set.
     * @return This builder for chaining.
     */
    public Builder setInstrument(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      instrument_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISIN, RIC, or symbol
     * </pre>
     *
     * <code>string instrument = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInstrument() {
      instrument_ = getDefaultInstance().getInstrument();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISIN, RIC, or symbol
     * </pre>
     *
     * <code>string instrument = 3;</code>
     * @param value The bytes for instrument to set.
     * @return This builder for chaining.
     */
    public Builder setInstrumentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      instrument_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object account_ = "";
    /**
     * <pre>
     * Trading account ID
     * </pre>
     *
     * <code>string account = 4;</code>
     * @return The account.
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Trading account ID
     * </pre>
     *
     * <code>string account = 4;</code>
     * @return The bytes for account.
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Trading account ID
     * </pre>
     *
     * <code>string account = 4;</code>
     * @param value The account to set.
     * @return This builder for chaining.
     */
    public Builder setAccount(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      account_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Trading account ID
     * </pre>
     *
     * <code>string account = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccount() {
      account_ = getDefaultInstance().getAccount();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Trading account ID
     * </pre>
     *
     * <code>string account = 4;</code>
     * @param value The bytes for account to set.
     * @return This builder for chaining.
     */
    public Builder setAccountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      account_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object counterparty_ = "";
    /**
     * <pre>
     * Broker/Dealer/Exchange
     * </pre>
     *
     * <code>string counterparty = 5;</code>
     * @return The counterparty.
     */
    public java.lang.String getCounterparty() {
      java.lang.Object ref = counterparty_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        counterparty_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Broker/Dealer/Exchange
     * </pre>
     *
     * <code>string counterparty = 5;</code>
     * @return The bytes for counterparty.
     */
    public com.google.protobuf.ByteString
        getCounterpartyBytes() {
      java.lang.Object ref = counterparty_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        counterparty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Broker/Dealer/Exchange
     * </pre>
     *
     * <code>string counterparty = 5;</code>
     * @param value The counterparty to set.
     * @return This builder for chaining.
     */
    public Builder setCounterparty(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      counterparty_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Broker/Dealer/Exchange
     * </pre>
     *
     * <code>string counterparty = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCounterparty() {
      counterparty_ = getDefaultInstance().getCounterparty();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Broker/Dealer/Exchange
     * </pre>
     *
     * <code>string counterparty = 5;</code>
     * @param value The bytes for counterparty to set.
     * @return This builder for chaining.
     */
    public Builder setCounterpartyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      counterparty_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private double quantity_ ;
    /**
     * <pre>
     * Executed quantity
     * </pre>
     *
     * <code>double quantity = 6;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public double getQuantity() {
      return quantity_;
    }
    /**
     * <pre>
     * Executed quantity
     * </pre>
     *
     * <code>double quantity = 6;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(double value) {
      
      quantity_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Executed quantity
     * </pre>
     *
     * <code>double quantity = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000020);
      quantity_ = 0D;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <pre>
     * Execution price
     * </pre>
     *
     * <code>double price = 7;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }
    /**
     * <pre>
     * Execution price
     * </pre>
     *
     * <code>double price = 7;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Execution price
     * </pre>
     *
     * <code>double price = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000040);
      price_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object side_ = "";
    /**
     * <pre>
     * BUY or SELL
     * </pre>
     *
     * <code>string side = 8;</code>
     * @return The side.
     */
    public java.lang.String getSide() {
      java.lang.Object ref = side_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        side_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * BUY or SELL
     * </pre>
     *
     * <code>string side = 8;</code>
     * @return The bytes for side.
     */
    public com.google.protobuf.ByteString
        getSideBytes() {
      java.lang.Object ref = side_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        side_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * BUY or SELL
     * </pre>
     *
     * <code>string side = 8;</code>
     * @param value The side to set.
     * @return This builder for chaining.
     */
    public Builder setSide(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      side_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BUY or SELL
     * </pre>
     *
     * <code>string side = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSide() {
      side_ = getDefaultInstance().getSide();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BUY or SELL
     * </pre>
     *
     * <code>string side = 8;</code>
     * @param value The bytes for side to set.
     * @return This builder for chaining.
     */
    public Builder setSideBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      side_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object venue_ = "";
    /**
     * <pre>
     * Market or exchange (e.g., LSE, NYSE)
     * </pre>
     *
     * <code>string venue = 9;</code>
     * @return The venue.
     */
    public java.lang.String getVenue() {
      java.lang.Object ref = venue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        venue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Market or exchange (e.g., LSE, NYSE)
     * </pre>
     *
     * <code>string venue = 9;</code>
     * @return The bytes for venue.
     */
    public com.google.protobuf.ByteString
        getVenueBytes() {
      java.lang.Object ref = venue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        venue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Market or exchange (e.g., LSE, NYSE)
     * </pre>
     *
     * <code>string venue = 9;</code>
     * @param value The venue to set.
     * @return This builder for chaining.
     */
    public Builder setVenue(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      venue_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Market or exchange (e.g., LSE, NYSE)
     * </pre>
     *
     * <code>string venue = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearVenue() {
      venue_ = getDefaultInstance().getVenue();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Market or exchange (e.g., LSE, NYSE)
     * </pre>
     *
     * <code>string venue = 9;</code>
     * @param value The bytes for venue to set.
     * @return This builder for chaining.
     */
    public Builder setVenueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      venue_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private long tradeTimestamp_ ;
    /**
     * <pre>
     * Execution timestamp (epoch millis)
     * </pre>
     *
     * <code>int64 tradeTimestamp = 10;</code>
     * @return The tradeTimestamp.
     */
    @java.lang.Override
    public long getTradeTimestamp() {
      return tradeTimestamp_;
    }
    /**
     * <pre>
     * Execution timestamp (epoch millis)
     * </pre>
     *
     * <code>int64 tradeTimestamp = 10;</code>
     * @param value The tradeTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTradeTimestamp(long value) {
      
      tradeTimestamp_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Execution timestamp (epoch millis)
     * </pre>
     *
     * <code>int64 tradeTimestamp = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTradeTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000200);
      tradeTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     * NEW, AMEND, CANCEL, FILLED, PARTIALLY_FILLED
     * </pre>
     *
     * <code>string status = 11;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * NEW, AMEND, CANCEL, FILLED, PARTIALLY_FILLED
     * </pre>
     *
     * <code>string status = 11;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * NEW, AMEND, CANCEL, FILLED, PARTIALLY_FILLED
     * </pre>
     *
     * <code>string status = 11;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * NEW, AMEND, CANCEL, FILLED, PARTIALLY_FILLED
     * </pre>
     *
     * <code>string status = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * NEW, AMEND, CANCEL, FILLED, PARTIALLY_FILLED
     * </pre>
     *
     * <code>string status = 11;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object regulatoryId_ = "";
    /**
     * <pre>
     * MiFID / SEC / local trade identifier
     * </pre>
     *
     * <code>string regulatoryId = 12;</code>
     * @return The regulatoryId.
     */
    public java.lang.String getRegulatoryId() {
      java.lang.Object ref = regulatoryId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        regulatoryId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * MiFID / SEC / local trade identifier
     * </pre>
     *
     * <code>string regulatoryId = 12;</code>
     * @return The bytes for regulatoryId.
     */
    public com.google.protobuf.ByteString
        getRegulatoryIdBytes() {
      java.lang.Object ref = regulatoryId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regulatoryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * MiFID / SEC / local trade identifier
     * </pre>
     *
     * <code>string regulatoryId = 12;</code>
     * @param value The regulatoryId to set.
     * @return This builder for chaining.
     */
    public Builder setRegulatoryId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      regulatoryId_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * MiFID / SEC / local trade identifier
     * </pre>
     *
     * <code>string regulatoryId = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegulatoryId() {
      regulatoryId_ = getDefaultInstance().getRegulatoryId();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * MiFID / SEC / local trade identifier
     * </pre>
     *
     * <code>string regulatoryId = 12;</code>
     * @param value The bytes for regulatoryId to set.
     * @return This builder for chaining.
     */
    public Builder setRegulatoryIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      regulatoryId_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.lang.Object traderId_ = "";
    /**
     * <pre>
     * Internal trader reference
     * </pre>
     *
     * <code>string traderId = 13;</code>
     * @return The traderId.
     */
    public java.lang.String getTraderId() {
      java.lang.Object ref = traderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Internal trader reference
     * </pre>
     *
     * <code>string traderId = 13;</code>
     * @return The bytes for traderId.
     */
    public com.google.protobuf.ByteString
        getTraderIdBytes() {
      java.lang.Object ref = traderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Internal trader reference
     * </pre>
     *
     * <code>string traderId = 13;</code>
     * @param value The traderId to set.
     * @return This builder for chaining.
     */
    public Builder setTraderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traderId_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Internal trader reference
     * </pre>
     *
     * <code>string traderId = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraderId() {
      traderId_ = getDefaultInstance().getTraderId();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Internal trader reference
     * </pre>
     *
     * <code>string traderId = 13;</code>
     * @param value The bytes for traderId to set.
     * @return This builder for chaining.
     */
    public Builder setTraderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traderId_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private java.lang.Object strategyTag_ = "";
    /**
     * <pre>
     * Algo strategy / manual / HFT
     * </pre>
     *
     * <code>string strategyTag = 14;</code>
     * @return The strategyTag.
     */
    public java.lang.String getStrategyTag() {
      java.lang.Object ref = strategyTag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        strategyTag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Algo strategy / manual / HFT
     * </pre>
     *
     * <code>string strategyTag = 14;</code>
     * @return The bytes for strategyTag.
     */
    public com.google.protobuf.ByteString
        getStrategyTagBytes() {
      java.lang.Object ref = strategyTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strategyTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Algo strategy / manual / HFT
     * </pre>
     *
     * <code>string strategyTag = 14;</code>
     * @param value The strategyTag to set.
     * @return This builder for chaining.
     */
    public Builder setStrategyTag(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      strategyTag_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Algo strategy / manual / HFT
     * </pre>
     *
     * <code>string strategyTag = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearStrategyTag() {
      strategyTag_ = getDefaultInstance().getStrategyTag();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Algo strategy / manual / HFT
     * </pre>
     *
     * <code>string strategyTag = 14;</code>
     * @param value The bytes for strategyTag to set.
     * @return This builder for chaining.
     */
    public Builder setStrategyTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      strategyTag_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }

    private java.lang.Object correlationId_ = "";
    /**
     * <pre>
     * For linking across events (e.g., parent-child orders)
     * </pre>
     *
     * <code>string correlationId = 15;</code>
     * @return The correlationId.
     */
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * For linking across events (e.g., parent-child orders)
     * </pre>
     *
     * <code>string correlationId = 15;</code>
     * @return The bytes for correlationId.
     */
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * For linking across events (e.g., parent-child orders)
     * </pre>
     *
     * <code>string correlationId = 15;</code>
     * @param value The correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      correlationId_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For linking across events (e.g., parent-child orders)
     * </pre>
     *
     * <code>string correlationId = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrelationId() {
      correlationId_ = getDefaultInstance().getCorrelationId();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For linking across events (e.g., parent-child orders)
     * </pre>
     *
     * <code>string correlationId = 15;</code>
     * @param value The bytes for correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      correlationId_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:iris.TradeEvent)
  }

  // @@protoc_insertion_point(class_scope:iris.TradeEvent)
  private static final org.jaiswarsecurities.iris.proto.TradeEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.jaiswarsecurities.iris.proto.TradeEvent();
  }

  public static org.jaiswarsecurities.iris.proto.TradeEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TradeEvent>
      PARSER = new com.google.protobuf.AbstractParser<TradeEvent>() {
    @java.lang.Override
    public TradeEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TradeEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TradeEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.jaiswarsecurities.iris.proto.TradeEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

